config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match 'users/:id/message' => 'users#message', :via => [:get, :post]
  match '/messages' => 'users#inbox', :via => [:get,:post]
  match '/messages/delete' => 'users#destroy_message', :via => [:delete]
  match '/myrides' => 'carpools#rides', :via => [:get,:post]
  match '/Currentlocation' => 'locations#map', :via => [:get,:post]

  resources :users do
     member do
    put "like", to: "users#upvote"
    put "Dislike", to: "users#downvote"
   end
  end
  resources :testimonials
  resources :locations
  resources :carpools do
    resources :passengers
    match 'mypassengers' => 'carpools#mypassengers', via: [:get, :post]
  end
  resources :cars
  match "/carpools/find" => "carpools#find" , :via => :post
  match "/carpools/search" => "carpools#search" , :via => :get
  root 'carpools#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

end

app/models/carpool.rb
class Carpool < ActiveRecord::Base
	belongs_to :user
	has_many :cars
	has_many :source, :dependent => :destroy
    has_many :destination, :dependent => :destroy
    has_many :seats, :dependent => :destroy
    has_many :preferences, :dependent => :destroy
    has_many :passengers
	accepts_nested_attributes_for :source, :allow_destroy => true
	accepts_nested_attributes_for :destination, :allow_destroy => true
	accepts_nested_attributes_for :seats, :allow_destroy => true
	accepts_nested_attributes_for :preferences, :allow_destroy => true

	validates :price, :luggage_size,:other,:car_id, :presence => :true
	validates_associated :seats
	validates_associated :destination
	validates_associated :source
	
end

app/controllers/carpools_controller.rb
class CarpoolsController < ApplicationController
  before_filter :authenticate_user!, :only => [:new, :find]
  before_action :find_carpool, :only => [:edit, :destroy, :update]
  def index
  	@carpools = Carpool.order("created_at DESC")
    @testimonials = Testimonial.all.order("created_at DESC")
  end

  def new
  	@carpool = current_user.carpools.build
  	@carpool.source.build
  	@carpool.destination.build
  	@carpool.seats.build
  	@carpool.preferences.build
  end

  def mypassengers
    @passengers= Carpool.find(params[:carpool_id]).passengers
  end


  def edit
    
  end

  def update
    #@carpool = current_user.carpools.build
    if @carpool.update(carpool_params)
      flash[:alert]= "Your carpool has been update"
      redirect_to @carpool
    else
      render('edit')
    end
  end

  def destroy
    @carpool.destroy
    flash[:alert]= "Your carpool has been deleted"
    redirect_to root_path
  end


  def create
  	@carpool= current_user.carpools.build(carpool_params)

  	if @carpool.save
      flash[:alert]= "Your carpool has been created"
  		redirect_to root_path
  	else
  		render 'new'
  	end

  end

  def find
    @source = params[:source]
    @destination = params[:destination]
    @carpools = Carpool.where("journey_date > ?", Date.today).where("user_id != ?",current_user.id)
    @location = Geocoder.coordinates(params[:source])
    #@location2 = Geocoder.coordinates(params[:destination])
   # @slat = @location[0]
    #@slong = @location[1]
    #@dlat = @location2[0]
    #@dlong = @location2[1] 
   # render :json => (@location[1])
  end

  def show
     @carpool= Carpool.find(params[:id])
     @sred = "No smoking" 
     @syellow = "Depends On the situation. Ask me"
     @sgreen = "You can smoke"
     @pred = "No pets please. Sorry" 
     @pyellow = "Depends On the pet. Ask me first"
     @pgreen = "All pets are welcome"
     @fred = "No eating in car" 
     @fyellow = "No crumbs in the car please. Eat neat"
     @fgreen = "Eat whenever you like"
     @mred = "I like a Quite ride" 
     @myellow = "Depends On the Kind of Music" 
     @mgreen = "I enjoy all kinds of music"

  end


  def rides
    @rides = current_user.carpools.order("updated_at DESC")
    @passengers = Passenger.where(:passenger => current_user.id)
     @location = current_user.locations.build
  end

private
 
 def carpool_params
 	params.require(:carpool).permit(:journey_date, :car_id, :luggage_size, :depature_time, :price, :other, source_attributes: [:id,:_destroy,:source, :lattitude, :longitude],destination_attributes: [:id,:_destroy,:destination, :lattitude, :longitude],seats_attributes: [:id,:_destroy,:seats], preferences_attributes: [:id,:_destroy,:music, :pets, :smoking, :ladies, :food])
 end

 def find_carpool
   @carpool =Carpool.find(params[:id])
   
 end

end

app/helpers/carpools_helper.rb
module CarpoolsHelper
end

app/views/carpools/_form.html.erb
<div class="create-carpool">
<p id="heading1">Register your carpool</p>

 <%= simple_form_for @carpool  do |c| %>
 <div id="step-1" class="step">
<span class="badge-success">Step 1</span>  
<div id="time-date" class="carpool"> 

 <span id="date" class="carpool"> 
 <%= c.input :journey_date,:label_html => { :class => 'left' }, start_year: Date.today.year,end_year: Date.today.year + 12 %> 
 </span>
 <span id="time" class="carpool"> 
 <%= c.input :depature_time %> 
 </span>
</div>
</div>

<div id="step-2" class="step">
<span class="badge-success">Step 2</span>  
<div id="price-laggage" class="carpool">  
 <span id="price" class="carpool"> 
 <%= c.input :price %>
 </span>
 <span id="luggage" class="carpool"> 
 <%= c.input :luggage_size, collection: 1..50 %>
 
 
  <%= c.input :car_id, collection: Car.where(:user_id => current_user.id).map {|p| [p.brand,p.id]}, as: :select %>
 </span>
 <span id="seats" class="carpool"> 
  <%= c.simple_fields_for :seats do |seat| %>
       <%= seat.input :seats%>
   <% end %>
 </span>
 <span id="other" class="carpool"> 
  <%= c.input :other %>
 </span>

</div>
</div>

<div id="step-3" class="step">
<span class="badge-success">Step 3</span> 
<div id="source-destination" class="carpool">
  <span id="source-field" class="carpool"> 
     <%= c.simple_fields_for :source,:html => { :class => 'right' } do |s| %>
         <%= s.input :source, input_html: {id: "source"} %>
         <%= s.input :longitude, as: :hidden %>
         <%= s.input :latitude, as: :hidden %>
     <% end %>
  </span>

  <span id="destination-field" class="carpool"> 
     <%= c.simple_fields_for :destination do |d| %>
         <%= d.input :destination, input_html: {id: "destination"} %>
         <%= d.input :longitude, as: :hidden %>
         <%= d.input :latitude, as: :hidden %>
     <% end %>
  </span>
</div>
</div>

<div id="step-4" class="step">
<span class="badge-success">Step 4</span> 
<div id="preferences" class="carpool"> 
    <span id="music" class="carpool"> 
       <%= c.simple_fields_for :preferences do |p| %>
           <%= p.input :music, 
                :as => :select, 
                :collection => [['I like a Quite ride','mred'],['Depends On the Kind of Music','myellow'],['I enjoy all kinds of music','mgreen']], 
                :include_blank => false, 
                :label => "Music" %>
    </span>

    <span id="pets" class="carpool"> 
            <%= p.input :pets, 
                :as => :select, 
                :collection => [['No pets please. Sorry','pred'],['Depends On the pet. Ask me first','pyellow'],['All pets are welcome','pgreen']], 
                :include_blank => false, 
                :label => "Pets" %>
    </span>

    <span id="smoking" class="carpool"> 
            <%= p.input :smoking, 
                :as => :select, 
                :collection => [['No smoking','sred'],['Depends On the situation. Ask me','syellow'],['You can smoke','sgreen']], 
                :include_blank => false, 
                :label => "Smoking" %>
    </span>

    <span id="food" class="carpool"> 
            <%= p.input :food, 
                :as => :select, 
                :collection => [['No eating in car','fred'],['No crumbs in the car please. Eat neat','fyellow'],['Eat whenever you like','fgreen']], 
                :include_blank => false, 
                :label => "Food" %>
    </span>
   
    <span id="ladies" class="carpool"> 
    <%= p.input :ladies, as: :boolean %>
       <% end %>
    </span>
</div>
</div>

<div id="button-sub">
    <span id="bt" class="carpool"> 
     <%= c.button :submit ,:class => "btn btn-blue btn-lg"%>
      <% end %>
    </span>
</div>

</div>

<div id="map-canvas2"></div>

app/views/carpools/_getMap.js.erb
$(function() {
  source = document.getElementById('source').innerHTML.trim();
  dest = document.getElementById('dest').innerHTML.trim();
  Map.initialize()
  Map.calcRoute(source,dest)
  
});

app/views/carpools/edit.html.erb
<%=  render('form') %>

app/views/carpools/find.html.erb
<div id="find-rides">
<p id="heading1">Carpool search</p>


<% t=0 %>
<table class="table-minimal">
        <thead>
          <tr>
            <th>User</th>
            <th>Source</th>
            <th>Destination</th>
            <th>Journey Date</th>
            <th>Available Seats</th>
            <th>Options</th>
          </tr>
        </thead>
<% @carpools.each do |carpool| %>
  <% if carpool.seats.first.seats >  0 %>
    <% carpool.source.first.source %> <!--source -->
    <% carpool.destination.first.destination %> <!--destination -->
    <% distance = ((carpool.source.first.distance_to(carpool.destination.first, :km)).round(2)) %>  <!--distance -->
    <% sDis = ((distance * 0.50)).round(2) %>  <!--sDis -->
    <% dDis = ((distance * 0.50)).round(2) %> <!--dDis -->
    <% source= ((carpool.source.first.distance_to(@source, :km) ).round(2)) %> 
    
    <% dest= ((carpool.destination.first.distance_to(@destination, :km) ).round(2)) %> 
   
    <% if source <= sDis %>
      <% if dest <= dDis %>

      

        <tbody>
          <tr>
            <td><%= link_to "#{carpool.user.username}", carpool.user %> </td>
            <td><%= carpool.source.first.source %> <!--source --></td>
            <td><%= carpool.destination.first.destination %><!--destination --></td>
            <td><%= carpool.journey_date %></td>
            <td><%= carpool.seats.first.seats %></td>
            <td><%= link_to "show", carpool , method: :get ,:class=>" btn btn-blue btn-lg log-btn"%></td>
          </tr>
        </tbody>
     
      <% t=t+1 %>
        <br>
      <% end %>
    <% end %> 
  <% end %>
<% end %>

<% if t==0 %>
  <h3> No results </h3>
<% end %>
 </table>

</div>

app/views/carpools/index.html.erb
<!--/mobile div for the buttons -->
  <div class="mobile-div">

      <%= link_to new_carpool_path, method: :get do%>
        <i class="fa fa-car btn offer-ride btn-inverse" >Offer Ride</i>
      <% end %>


  </div>
<!--/mobile div for the buttons -->

<!--here Image parallax start -->
  <div id="js-parallax-window" class="parallax-window">

    <div id="js-parallax-background" class="parallax-background" >

      <%= image_tag("parallax.jpg") %>
    </div>
  </div>
<!--image parallax end -->

<!-- search form -->
<div class="find-rides-main">
  <div class="find-rides">
      <%= form_tag(:action => 'find') do %>

        <span id="source-span" class="float_label">
        <%= text_field_tag (:source), nil, :required => true,:placeholder => ""%>
        <label id="find-enter-source">Enter source</label>
        </span>

        <span id="destination-span" class="float_label">
        <%= text_field_tag (:destination), nil, :required => true ,:placeholder => ""%>
        <label id="find-enter-destination">Enter destination</label>
        </span>


       <%= submit_tag "Search", :class=> "btn btn-blue", :id=> "search-button" %>
      <% end %>
  </div>
   <div id="map-canvas2"></div>
</div>
<!--/search form -->

<!-- description start -->
  <article class="type-system-slab test">
    <h2>ShareRide is an online carpooling application in which people can share rides. Our main aim is to allows passengers to travel comfortably and in a secure way while saving costs.
    </h2>
  </article>
<!--/ description start -->

<!-- paralax working start -->
  <div class="content">
       <%= image_tag("how.jpg" ) %>
        <div class="working-pics">
          <div class="row img-row">
            <figure class="columns space"><%= image_tag("1.jpg" ) %></figure>
            <figure class="columns space"><%= image_tag("arrow.png") %></figure>
            <figure class="columns space"><%= image_tag("2.jpg") %></figure>
            <figure class="columns space"><%= image_tag("arrow.png") %></figure>
            <figure class="columns space"><%= image_tag("3.jpg") %></figure>
            <figure class="columns space"><%= image_tag("arrow.png") %></figure>
            <figure class="columns space"><%= image_tag("4.jpg") %></figure>
            <figure class="columns space"><%= image_tag("arrow.png") %></figure>
            <figure class="columns space"><%= image_tag("5.jpg") %></figure>
          </div>
        </div>
  </div>
<!-- paralax working end -->

<div class="ride_testimonial">
<!-- recent rides start-->
    <div class="recent-rides">
    <p class="heading dancing-script">Recent Rides</p>
    <div id="buttons"><%= link_to image_tag("up_arrow.png",:id => "prev1") %> </div> 
      <div id="carousel1">
        <div id="slides1">
          <ul style="margin-top:9px">
             <% if !@carpools.empty? %>
             <% @carpools.each do |c| %>
             <li class="slide1">
              <span class="slide-rides"><% if c.user.picture.url == "blank.png" && c.user.provider=="facebook"%>   
              <%= image_tag "http://graph.facebook.com/#{c.user.uid}/picture?width=100&height=100",:style=> "border-radius:50%;border:5px solid #18BD9D" %>
              <% else %>
                <%= image_tag c.user.picture.url, :style=> "width:75px;height:75px;border-radius:50%;border:5px solid #18BD9D"%>
              <% end %>
              </span>
              <span class="slide-rides">
              <p><span class="" style="color:#18BD9D;">Source</span> <%= c.source.first.source %></p>
              </span>
              <span class="slide-rides">
              <p> <span class="" style="color:#18BD9D;">Destination</span> <%= c.destination.first.destination %></p>
              </span>
              <span class="slide-rides">
              <p><span class="" style="color:#18BD9D;">Date</span><br><%= c.journey_date.strftime("%d, %B, %Y") %> </p>
              </span>
              <span class="slide-rides">
              <p><span class="" style="color:#18BD9D;">Price</span><br> <%= c.price %> ₹ </p>
              </span>
             </li>
             <% end %>  
             <% end %>
          </ul>
        </div>
      </div>
      <div id="buttons"><%= link_to image_tag("down_arrow.png",:id => "next1") %> </div>
    </div>
<!-- testimonial start-->
   <div class="testimonial">
   <p class="heading dancing-script">Testimonials</p>
    <div id="buttons"><%= link_to image_tag("up_arrow.png",:id => "prev2") %> </div>
        <div id="carousel2">
        <div id="slides">
            <ul>
            <% if !@testimonials.empty? %>
            <% @testimonials.each do |t| %>
            <li class="slide">
              <% if t.user.picture.url == "blank.png" && t.user.provider=="facebook"%>   
                  <%= image_tag "http://graph.facebook.com/#{t.user.uid}/picture?width=120&height=120",:style=> "border-radius:50%;border:5px solid #18BD9D" %>
              <% else %>
                <%= image_tag t.user.picture.url, :style=> "width:120px;height:120px;border-radius:50%;border:5px solid #18BD9D"%>
              <% end %>

               <h1 id="name"><%= t.user.username %></h1>
               <p><%= t.message %></p>
            </li>
             <% end %>
             <% end %>
            </ul>
        </div>
        </div>
        <div id="buttons"><%= link_to image_tag("down_arrow.png",:id => "next2") %> </div>
    </div>
</div>
<!-- / testimonial-->
<!-- ride and testimonial -->

app/views/carpools/mypassengers.html.erb
<div class="passenger-list">
<p id="heading1">Passenger details</p>

<% if @passengers.count != 0 %>

	<% @passengers.each do |pas| %>
	  <% user = User.find(pas.passenger) %>
	<% if user.picture.url == "blank.png" && user.provider=="facebook"%>   
	   <%= image_tag "http://graph.facebook.com/#{user.uid}/picture?width=150&height=150" %>
	<% else %>
	    <%= image_tag user.picture.url, :style=>"width=150&height=150"%>
	<% end %>
	<p><%= user.phone_number%><p>
	<p><%=link_to  "#{user.username}", user_path(pas.passenger) %></p>
	<p><%= user.email%></p>

	<hr>
	<!-- dp name phonu email  -->
	<% end %>
<% else %>
<p id="heading2">No passenger has booked your carpool </p>
<%end %>
</div>

app/views/carpools/new.html.erb
<h1>Carpools#new</h1>
<p>Find me in app/views/carpools/new.html.erb</p>

app/views/carpools/rides.html.erb
<div class="my-rides">
<p id="heading1">Rides and publish location</p>
<div class="publish-location-form">
<%= render('locations/form') %>
</div>

<ul class="accordion-tabs-minimal">
  <li class="tab-header-and-content">
    <a href="#" class="tab-link is-active font3">Created Carpools</a>
    <div class="tab-content">
            <% @rides.each do |r| %>
        <div id="tab-main-content">
            <%= link_to carpool_path(r.id),method: :get do %>
            <span class="test font2" id="tab-source"> <span class="font3"> Source:</span><%= r.source.first.source %></span>
            <span class="test font2" id="tab-destination"><span class="font3">Destination:</span><%= r.destination.first.destination %></span>
            <span class="test" id="tab-date"><%= r.journey_date.strftime("%d, %B, %Y") %></span>
            <span class="test" id="tab-time"><%= r.depature_time.strftime("%I:%M %p") %></span>
            <span class="test" id="tab-created">Created <%= time_ago_in_words(r.updated_at)%> ago</span>
            <% end %>
            <span class="test" id="tab-passenger"> Passengers<%= r.passengers.size %></span>
            
            <span class="table-button"><%= link_to "edit", edit_carpool_path(r.id) ,:class => "btn btn-blue btn-sm"%>
            </span>
            <span class="table-button"><%= link_to "view passengers", carpool_mypassengers_path(r.id) ,:class => "btn btn-yellow btn-sm"%>
            </span>
            <span class="table-button"><%= link_to 'Delete', carpool_path(r.id),
                data: {confirm: "Are you sure?"}, :method => :delete ,:class => "btn btn-red btn-sm" %>
            </span>
         
       
        </div>  
        <% end %>  
    </div>
  </li>
  <li class="tab-header-and-content">
    <a href="#" class="tab-link font3">Booked Carpools</a>
    <div class="tab-content">
          <% @passengers.each do |pas| %>
          <% user = User.find(pas.passenger) %>
          <% carpool = Carpool.find(pas.carpool_id) %>
          <div id="created">
          <span class="created-tab font2"><span class="font3"> Source : </span><%= carpool.source.first.source%></span>
          <span class="created-tab font2"><span class="font3">Destination : </span><%= carpool.destination.first.destination%></span>
          <span class="created-tab"><%= carpool.journey_date.strftime("%d, %B, %Y") %></span>
          <span class="created-tab"><%= carpool.depature_time.strftime("%I:%M %p") %></span>
          <span class="font2" id="user-created"><%=link_to  "#{carpool.user.username}", user_path(carpool.user.id),method: :get %></span>
          <span class="created-button">
          <%= link_to 'Show', carpool_path(carpool.id), method: :get,:class=>"btn btn-blue btn-sm" %>
          </span>
          <span class="created-button">
          <%= link_to 'Delete', carpool_passenger_path(carpool.id,user.id), method: :delete, data: {confirm: "Are you sure?"},:class=>"btn btn-red btn-sm" %>
          </span>
          <span class="created-button">
          <% if Location.where(:user_id => carpool.user.id).size > 0 %>
           <%= link_to "see location", Currentlocation_path(carpool.id) ,method: :get,:class => "btn btn-blue btn-sm"%>
           <% end %>      
          </span>
          </div>

         <% end %>
        </tbody>
      </table>
    </div>
  </li>
</ul>
</div>

app/views/carpools/show.html.erb
<div id="show-carpool">

<div id="show-first">
<p id="heading1">Carpool details </p>
<br>
	<div id="map-canvas">
	  
	</div>

	<% content_for :head do %>
	  <script type="text/javascript">
	    <%= render 'carpools/getMap.js.erb' %>
	  </script>
	<% end %>

	<div id="show-user-details">
		<span class="show-users">
		<% if @carpool.user.picture.url == "blank.png" && @carpool.user.provider=="facebook"%>   
		  <%= image_tag "http://graph.facebook.com/#{@carpool.user.uid}/picture?width=120&height=120",:class=>"img-size"%>
		<% else %>
		  <%= image_tag @carpool.user.picture.url, :class=>"img-size"%>
		<% end %>
		</span>

		<span class="show-users">
		<span>Owner:</span> <%= link_to "#{@carpool.user.username}", @carpool.user %> 
		</span>
		<span class="show-users"> 
		<span>Email:</span> <%= @carpool.user.email %> <br>
		</span>
		<span class="show-users"> 
		<span>Phone no:</span> <%= @carpool.user.phone_number %> <br>
		</span>
		<span class="show-users"> 
		<span>Likes:</span> <%= @carpool.user.get_upvotes.size %> <br>
		</span>

		<div class="show-users">
		<span style="text-align:left">Preferences: </span>
		<br/>
			<span class="show-u-preference tooltip-item" style="margin-left:10px"><%= image_tag("#{@carpool.preferences.first.music}.png")   %> 
				<div class="tooltip">
				     
				    <p><%= instance_variable_get("@#{@carpool.preferences.first.music}") %></p>
				</div>
			</span>
			<span class="show-u-preference tooltip-item"><%=  image_tag("#{@carpool.preferences.first.food}.png") %> 
				<div class="tooltip">
				    <p><%= instance_variable_get("@#{@carpool.preferences.first.food}")%></p>
				</div>
			</span>
			<span class="show-u-preference tooltip-item"><%= image_tag("#{@carpool.preferences.first.pets}.png")  %>
				<div class="tooltip">
				    <p><%= instance_variable_get("@#{@carpool.preferences.first.pets}")%></p>
				</div>
			</span> 
			<span class="show-u-preference tooltip-item"><%= image_tag("#{@carpool.preferences.first.smoking}.png") %>
				<div class="tooltip">
				    <p><%= instance_variable_get("@#{@carpool.preferences.first.smoking}")%></p>
				</div>
			</span>
			
		</div>
	</div>
</div>

<div id="show-user-trip-1">
	<div id="show-user-trip">

		<div class="users-trip" id="source">
		 <%= @carpool.source.first.source %> 
		</div>
		<div class="users-trip1" id="source">
		<i class="fa fa-long-arrow-right fa-2x"></i>
		</div>
		<div class="users-trip" id="dest">
		 <%= @carpool.destination.first.destination %> 
		</div>
	</div>

	<div class="show-other">
	<span class="show-u-other font2"><span>seats:</span> <%= @carpool.seats.first.seats %></span>
	<span class="show-u-other font2"><span>luggage: </span> <%= @carpool.luggage_size %><span> Kg</span> </span>
	
	</div>

</div>


<div class="show-date-time font2">
	<span class="date-time">
		<i class="fa fa-calendar fa-2x"></i> 
		<span>journey date: </span> 
		<%= @carpool.journey_date.strftime("%d, %B, %Y") %>
	</span>
	<span class="date-time">
		<i class="fa fa-clock-o fa-2x"></i>
		<span>depature time: </span> 
		<%= @carpool.depature_time.strftime("%I:%M %p") %> 
	</span>
	
</div>

<div class="date-time-other font2"><span>More infrmation: </span> <%=  @carpool.other %>
</div>


<!-- I have changed if loop for validating booking -->
<div class="book-button">
<span id="show-button">
<% if @carpool.user.id != current_user.id && (Passenger.where(:carpool_id => @carpool.id).where(:passenger => current_user.id).size) == 0%>
<%= render('passengers/form') %>
<% end %>
</span>
</div>


</div>