config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match 'users/:id/message' => 'users#message', :via => [:get, :post]
  match '/messages' => 'users#inbox', :via => [:get,:post]
  match '/messages/delete' => 'users#destroy_message', :via => [:delete]
  match '/myrides' => 'carpools#rides', :via => [:get,:post]
  match '/Currentlocation' => 'locations#map', :via => [:get,:post]

  resources :users do
     member do
    put "like", to: "users#upvote"
    put "Dislike", to: "users#downvote"
   end
  end
  resources :testimonials
  resources :locations
  resources :carpools do
    resources :passengers
    match 'mypassengers' => 'carpools#mypassengers', via: [:get, :post]
  end
  resources :cars
  match "/carpools/find" => "carpools#find" , :via => :post
  match "/carpools/search" => "carpools#search" , :via => :get
  root 'carpools#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

end

app/models/car.rb
class Car < ActiveRecord::Base
	belongs_to :user
	belongs_to :carpool
	has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }
    validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

    validates :brand, :model, :color, :seats, :presence => :true
    											
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
    before_filter :find_car, only: [:show, :edit,:update, :destroy, :delete]

	def index
		@cars = Car.where(:user_id => current_user.id)
	end

	def new
		@car= current_user.cars.build
	end

	def create
    @car= current_user.cars.create(car_params)
    if @car.save
      flash[:alert]= "Your car has been created"
   	  redirect_to cars_path
    else
      @errors = @car.errors.full_messages
   	  render 'new'
    end
	end

  def show
     
  end

  def edit

  end

  def update
    if @car.update(car_params)
      flash[:alert]= "Your car has been updated"
    	redirect_to cars_path
    else
    	render 'edit'
    end
  end

  def delete

  end
  def destroy
     @car.destroy
     flash[:alert]= "Your car has been deleted"
     redirect_to cars_path
  end

	private

	def car_params
    params.require(:car).permit(:brand, :model, :color, :seats, :picture)
	end

	def find_car
    @car= Car.find(params[:id])
	end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<p id="heading1">Edit your car</p>

<div id="car-main">

 <%= simple_form_for @car, :html => { :multipart => true } do |f| %>

	<span class="car-row">
     
	  <span class="add-car"><%= f.input :brand %></span>
	  <span class="add-car"><%= f.input :color %></span>
	 </span>

	<span class="car-row">
	  <span class="add-car"><%= f.input :model %></span>
	  <span class="add-car"><%= f.input :seats %></span>
	</span>

	<span class="car-row">
	  <span class="add-car"><%= f.input :picture, as: :file %></span>
	  <span class="add-car"><%= f.button :submit ,:class => "btn btn-blue btn-lg"%></span>
	  <% end %>
	</span>
</div>

app/views/cars/edit.html.erb
<%= render('form') %>

app/views/cars/index.html.erb
<div id="car-show-main">
<p id="heading1">Car information</p>
<span class="add-car-button"> <%= link_to "Add Car", new_car_path ,:id=>"new",:class=>"btn btn-blue btn-lg "%></span>
<br>
<br>
<hr>
<% if !@cars.empty?  %>
	<% @cars.each do |car| %>
		 <% if car.user.id == current_user.id %>
	<div id="show-car">
		<div id="car-show-avatar">
			<div class="car-avatar">
			<%= image_tag car.picture.url(:medium) %>
			</div>
		</div>
		<div id="car-show-info">
			 <span id="car-show-name" class="font1">
			 	<%= link_to "#{car.brand}", car %>
			 </span>
			 <span id="car-show-button">
				 <%= link_to 'edit', edit_car_path(car),method: :get,:class=>"btn btn-blue btn-sm" %>
				 <%= link_to 'delete', car, method: :delete, data: {confirm: "Are you sure?"},:class=>"btn btn-red btn-sm" %>
			 </span>
			
		</div>
	</div>	
 <% end %>
			<% end %>
<% else %>
  <p id="heading1"> No car to display </p> <br>

<% end %>
</div>

app/views/cars/new.html.erb
<div class="error">
<% if @errors %>
<p> <%=pluralize(@errors.size, 'Error') %> prevented the form from being submitted </p>
<% end %>
</div>
<%= render('form') %>

app/views/cars/show.html.erb
<div id="show-car-details">
	<span id="car-details-img">
		<div class="car-avatar">
		<%= image_tag @car.picture.url(:medium) %>
		</div>
	</span>
	<span id="car-details-main" class="font2">
		Brand : <%= @car.brand %> <br>
		Color : <%= @car.color %> <br>
		Model : <%= @car.model %> <br>
		Seats : <%= @car.seats %> <br>
	</span>
</div>