config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match 'users/:id/message' => 'users#message', :via => [:get, :post]
  match '/messages' => 'users#inbox', :via => [:get,:post]
  match '/messages/delete' => 'users#destroy_message', :via => [:delete]
  match '/myrides' => 'carpools#rides', :via => [:get,:post]
  match '/Currentlocation' => 'locations#map', :via => [:get,:post]

  resources :users do
     member do
    put "like", to: "users#upvote"
    put "Dislike", to: "users#downvote"
   end
  end
  resources :testimonials
  resources :locations
  resources :carpools do
    resources :passengers
    match 'mypassengers' => 'carpools#mypassengers', via: [:get, :post]
  end
  resources :cars
  match "/carpools/find" => "carpools#find" , :via => :post
  match "/carpools/search" => "carpools#search" , :via => :get
  root 'carpools#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

end

app/models/testimonial.rb
class Testimonial < ActiveRecord::Base
	belongs_to :user

	validates :message, :presence => true

end

app/controllers/testimonials_controller.rb
class TestimonialsController < ApplicationController
	before_action :find_testimonial , :only => [:edit, :update, :destroy]
    def index
    	@testimonials=Testimonial.where(:user_id => current_user.id)
        @testimonial = current_user.testimonials.build
    end

	def create
        @testimonial = current_user.testimonials.create(testimonial_params)
        if @testimonial.save
            flash[:alert]= "Your testimonial has posted"
            redirect_to testimonials_path
        else
          flash[:alert]= "Your message cant be blank"
             redirect_to testimonials_path
        end
	end

	def new
     @testimonial = current_user.testimonials.build
	end

    def edit

    end

    def update
      if @testimonial.update(testimonial_params)
        flash[:alert]= "Your testimonial has been updated"
        redirect_to testimonials_path
     else
        render 'edit'
      end
    end

     def destroy
       @testimonial.destroy
       flash[:alert]= "Your testimonial has been deleted"
       redirect_to testimonials_path

    end
	private

	def find_testimonial
        @testimonial =Testimonial.find(params[:id])
	end
	


	def testimonial_params
		params.require(:testimonial).permit(:message)
	end
end

app/helpers/testimonials_helper.rb
module TestimonialsHelper
end

app/views/testimonials/_form.html.erb
<div class="testimonial-add">
<%=  simple_form_for @testimonial do |t| %>
  <%= t.input :message %>
 <center><%= t.button :submit ,:class => "btn btn-blue btn-lg" %></center>
<% end %>
</div>

app/views/testimonials/edit.html.erb
<%= render('form') %>

app/views/testimonials/index.html.erb
<div class="testimonial-add">
	<div id="test-add-content">
		<%= render('form') %>
	</div>
	<div class="testimonial-message">
		<% @testimonials.each do |t| %><br><hr>
		<span class="message-body"><%= t.message %> 
		</span>
		<span class="message-button1"><%= link_to 'edit', edit_testimonial_path(t),:class => "btn btn-blue btn-sm" %>
		</span>
		<span class="message-button1"><%= link_to 'delete', t, method: :delete, data: {confirm: "Are you sure?"},:class => "btn btn-red btn-sm" %>
		</span>
		<% end %>
	</div>
</div>

app/views/testimonials/new.html.erb
  <%= render('form') %>