config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  match 'users/:id/message' => 'users#message', :via => [:get, :post]
  match '/messages' => 'users#inbox', :via => [:get,:post]
  match '/messages/delete' => 'users#destroy_message', :via => [:delete]
  match '/myrides' => 'carpools#rides', :via => [:get,:post]
  match '/Currentlocation' => 'locations#map', :via => [:get,:post]

  resources :users do
     member do
    put "like", to: "users#upvote"
    put "Dislike", to: "users#downvote"
   end
  end
  resources :testimonials
  resources :locations
  resources :carpools do
    resources :passengers
    match 'mypassengers' => 'carpools#mypassengers', via: [:get, :post]
  end
  resources :cars
  match "/carpools/find" => "carpools#find" , :via => :post
  match "/carpools/search" => "carpools#search" , :via => :get
  root 'carpools#index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>CarpoolApp</title>
<%= Gon::Base.render_data({}) %>
<meta name="viewport" content="initial-scale=1.0, user-scalable=no">
<meta charset="utf-8">
<!-- <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true"></script>  -->
 <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&signed_in=true&libraries=places"></script>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>

<%= yield :head %>
</head>
<body>
<!--
<% if notice %>
<p class="notice"><%= notice %></p>
<% end %>
-->




<!-- Header start -->
<nav class="scrolled">
 
     <%= link_to image_tag("logo.png",:class => "logo"), root_path, method: :get ,:style=> "margin-top:0px;"%>
     
  <ul>
     <% if user_signed_in? %>
     
    <li id="offer-ride-desktop" class="nav-link">


      <%= link_to '<i class="fa fa-car"></i> offer ride'.html_safe, new_carpool_path, method: :get , :class=>'btn btn-inverse btn-lg'%>
    </li>


    <% if current_user.received_messages.unreaded.size > 0 %>
    <li class="nav-link envolpe1"><%= link_to '<i class="fa fa-envelope" style="color:red"></i>'.html_safe, messages_path,method: :get, class: 'fa-fw fa-3x'%>
    <span id="notification-num">
     <%= "[#{current_user.received_messages.unreaded.size}]" %>
    </span>
    </li>
  <% else %>
  <li class="nav-link envolpe1"><%= link_to '<i class="fa fa-envelope"></i>'.html_safe, messages_path,method: :get, class: 'fa-fw fa-3x'%>
      </li>

  <% end %>







    <li class="drop">
      <div class="dropdown">
        <div class="dropdown-container">
          <a class="dropdown-button">
            <figure class="avatar">
              <div class="avatar_pic">
              <% if current_user.picture.url == "blank.png" && current_user.provider=="facebook"%>
              
               <%= image_tag "http://graph.facebook.com/#{current_user.uid}/picture?width=150&height=150" %>
              
              <% else %>
              <%= image_tag current_user.picture.url(:medium), :style=>"height: 53px;"%>
              <% end %>
              </div>
            </figure>
          </a>
          <ul class="dropdown-menu dropdown-select transbox">
            <li> <%= link_to "My Account", edit_user_registration_path(current_user), method: :get %> </li>
            <li> <%= link_to "My Cars", cars_path, method: :get %> </li>
            <li><%= link_to "testimonials", testimonials_path, method: :get %> </li>
            <li><%= link_to "My Rides", myrides_path, method: :get %></li>
            <li> <%= link_to "LogOut", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    </li>




      

    <% else %>
    <li class="nav-link">
     

      <%= link_to '<i class="fa fa-user fa-fw fa-2x"></i> Log in'.html_safe,new_user_session_path%>

      
    </li>
    
      <li class="nav-link">
      <%= link_to '<i class="fa fa-user-plus fa-fw fa-2x"></i> Sign Up '.html_safe, new_user_registration_path%>
    </li>

    <% end %>
  </ul>
</nav>


<!-- Header end -->

<% if notice %>
    <div id="notice_wrapper">
        <p class="notice"><%= notice %></p>
    </div>
<% elsif %>
    <div id="notice_wrapper">
    <% if alert %>
        <p class="alert"><%= alert %></p>
    <% end %>
    </div>
<% end %>

<div class= "errors">


</div>

<div id="yield-test">
<%= yield %>
</div>
<!-- footer start-->
<div class="footer-img">
<%= image_tag("img-footer.png", :alt => "rss feed") %>
</div>
<footer class="footer" role="contentinfo">
  <div class="footer-logo">
    <!-- <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/placeholder_logo_1.png" alt="Logo image"> -->
  </div>
   <h3 style="color:white;text-align:center;"> Follow Us </h3>
  <div class="footer-links">

    <ul>
      <li><h3>Amit Gude</h3></li>
      <li><a href="http://www.facebook.com/amit.gude">Facebook</a></li>
      <li><a href="https://twitter.com/AmitGude">Twitter</a></li>
      
    </ul>
    <ul>
      <li><h3>Wolfgang Furtado</h3></li>
      <li><a href="http://www.facebook.com/wolfgang.furtado10">Facebook</a></li>
      <li><a href="https://twitter.com/WolfgangFurtado">Twitter</a></li>
      
    </ul>
    <ul>
      <li><h3>Saeel Parulekar</h3></li>
      <li><a href="http://www.facebook.com/saeel.parulekar">Facebook</a></li>
      <li><a href="https://twitter.com/SaeelParulekar">Twitter</a></li>
      
    </ul>
  </div>


</footer>
<!-- footer end-->
</body>
</html>